name: Tests
on: push

jobs:
  build-and-run:
    name: Build and run tests
    runs-on: ubuntu-latest
    env:
        VYSE_PATH: "/home/runner/work/snap/snap/bin"
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install submodule dependencies 
        run:  git submodule update --init --recursive

      - name: Create build scripts
        run: mkdir -p bin && cd bin && 
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=true -DSTRESS_GC=true -DLOG_GC=false -DLOG_DIASM=false -DVYSE_MINSTACK=true

      - name: Build project and run tests
        run: cd bin && ninja && ./vm-test
